<div class="navbar">
	<ul class="nav navbar-nav">
		<li><a href="<?php echo BASE_URI; ?>/configuration/update">App Configuration Panel</a></li>
		<li><a href="<?php echo BASE_URI; ?>/scheduledSMS/update">SMS Configuration Panel</a></li>
		<li><a href="<?php echo BASE_URI; ?>/users">User Accounts</a></li>
		<li><a href="<?php echo BASE_URI; ?>/simulator">Two-Way SMS Simulator</a></li>
		<li><a href="<?php echo BASE_URI; ?>/scheduledSMSSimulator">One-Way SMS Simulator</a></li>
	</ul>
</div>
